version: '3'

services:
  server:
    build: ./server
    ports:
      - "12931:3000"
    volumes:
      - /home/panemiko/rpgs/armageddon:/app/db
    restart: unless-stopped
    
  web:
    build: ./web
    ports:
      - "12930:5173"
    depends_on:
      - server
    restart: unless-stopped
