version: '3'

services:
  server:
    build: ./server
    ports:
      - "${LOCAL_SERVER_PORT}:3000"
    volumes:
      - /home/panemiko/rpgs/armageddon:/app/db
    restart: unless-stopped
    
  web:
    build: ./web
    ports:
      - "${LOCAL_WEB_PORT}:5173"
    depends_on:
      - server
    restart: unless-stopped
